name: Split Monorepo Dev-Master

on:
  workflow_run:
    workflows:
      - "generate_split_changelog"
    types:
      - completed

jobs:
  provide_packages_json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    # see https://stackoverflow.com/a/62953566/1348344
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      -
        uses: actions/checkout@v2

      # required for matrix of packages set
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 7.4
            coverage: none

      -   uses: "ramsey/composer-install@v1"
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      # get package json list
      -
        id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - name: Download pusher
        uses: actions/download-artifact@v2
        with:
          name: get_pusher
      - name: Print the final result
        id: pusher_data
        shell: bash
        run: |
          echo "::set-output name=pusher::$(cat pusher.json)
          rm -rf pusher.json
      -
        uses: actions/checkout@v2
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of packages ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@1.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'kpicaza'
          split-repository-name: '${{ matrix.package }}'
          user-name: ${{fromJson(steps.pusher_data.pusher).name}}
          user-email: ${{fromJson(steps.pusher_data.pusher).email}}
          branch: "main"

      -
        if: "startsWith(github.ref, 'refs/tags/')"
        name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      -
        if: "startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Tagged Split of packages ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@1.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${{ steps.get_version.outputs.version }}
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'kpicaza'
          split-repository-name: '${{ matrix.package }}'
          user-name: ${{fromJson(steps.pusher_data.pusher).name}}
          user-email: ${{fromJson(steps.pusher_data.pusher).email}}
          branch: "main"
